name: "Restrict PR to a single commit"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"

jobs:
  # Only run on PR's not coming from a release branch
  run-if:
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: thebigredgeek/SingleCommit@0.0.2
